website_name: Diskover Configuration and Administration Guide
# Folder on the website, if you specify "folder" it will deploy this guide to https://docs.diskoverdata.com/folder
website_folder: diskover_configuration_and_administration_guide
# All documents need to be in shared folder
ordered_documents:
  - index_diskover_guides_header.md
  - guide_title_config_admin.md
  - intro_guide_intended_for_tech.md
  - intro_copyright.md
  - intro_tech_guides_main_intro.md
  - intro_tech_guides_use_cases.md
  - intro_tech_guides_aws_approved.md
  - intro_doc_conventions.md
  - user_roles_and_auth.md
  - path_translation.md
  - tags_intro.md
  - tags_application_methods_intro.md
  - tags_application_methods_autotag.md
  - tags_application_methods_diskover_api.md
  - tags_application_methods_harvest_plugin.md
  - tags_application_methods_manual.md
  - tags_migration.md
  - tags_display_in_ui.md
  - reporting_intro.md
  - reporting_smart_searches.md
  - reporting_cost_analysis.md
  - task_config_files.md
  - task_management.md
  - plugins_intro.md
  - plugins_unix_permissions.md
  - plugins_windows_owner.md
  - plugins_dupes_finder.md
  - plugins_autoclean.md
  - plugins_tag_copier.md
  - plugins_index_differential.md
  - plugins_index_autotag.md
  - plugins_illegalfilename.md
  - plugins_media_harvest.md
  - plugins_mediapulse_asset_creation.md
  - plugins_bam_harvest.md
  - plugins_display_extra_fields.md
  - plugins_diskover_web_file_actions.md
  - plugins_diskover_web_file_sequence.md
  - index_management_intro.md
  - index_management_diskover_web.md
  - index_management_elasticsearch.md
  - index_advanced.md 
  - backup_and_recovery_intro.md
  - backup_and_recovery_setup.md
  - backup_and_recovery_elasticsearch.md
  - backup_and_recovery_indexers.md
  - backup_and_recovery_diskover_web.md
  - maintenance_routine_intro.md
  - maintenance_routine_diskover_upgrade.md
  - maintenance_emergency_intro.md
  - maintenance_emergency_diskover_web.md
  - maintenance_emergency_elasticsearch.md
  - maintenance_emergency_elasticsearch_aws.md
  - support.md
  - contact.md
  - footer.md
