website_name: Diskover Configuration and Administration Guide
# Folder on the website, if you specify "folder" it will deploy this guide to https://docs.diskoverdata.com/folder
website_folder: diskover_configuration_and_administration_guide
# All documents need to be in shared folder
index_document: index_diskover_guides_header.md
ordered_documents:
  - intro_copyright.md
  - intro_guide_intended_for.md
  - intro_tech_guides_main_intro.md
  - intro_tech_guides_use_cases.md
  - intro_tech_guides_aws_approved.md
  - intro_doc_conventions.md
  










  - support.md
  - contact.md
  
