site_name: DiskoverData Guide
theme:
    name: 'material'
    favicon: 'images/favicon.ico'
    extra_css:
       - 'stylesheets/extra.css'
markdown_extensions:
    - mdx_breakless_lists
    - markdown_checklist.extension
    - nl2br
