site_name: DiskoverData Guide
theme:
    name: 'material'
    favicon: 'images/favicon.png'
    logo: 'images/logo.png'
    palette:
        scheme: slate
        primary: deep purple
        accent: yellow
markdown_extensions:
    - mdx_breakless_lists
    - markdown_checklist.extension
    - meta
    - toc:
        toc_depth: 3
