site_name: DiskoverData Guide
theme:
    name: 'material'
    favicon: 'images/favicon.ico'
    features:
        - navigation.tracking
    palette:
        scheme: slate
        primary: deep purple
        accent: yellow
markdown_extensions:
    - mdx_breakless_lists
    - markdown_checklist.extension
    - meta
    - toc:
        toc_depth: 3
extra_css:
    - css/extra.css
