site_name: DiskoverData Guide
theme:
    name: 'material'
    favicon: 'assets/images/favicon.png'
    logo: 'assets/images/logo.png'
    palette:
        scheme: default
        primary: cyan
        accent: red
markdown_extensions:
    - mdx_breakless_lists
    - pymdownx.tasklist
    - meta
    - toc:
        toc_depth: 3
extra_css:
    - assets/css/extra.css
extra_javascript:
    - assets/js/extra.js
