site_name: DiskoverData Guide
theme:
    name: 'material'
    favicon: 'assets/images/favicon.png'
    logo: 'assets/images/logo.png'
    palette:
        scheme: white
        primary: light grey
        accent: red
markdown_extensions:
    - mdx_breakless_lists
    - markdown_checklist.extension
    - meta
    - toc:
        toc_depth: 3
