site_name: DiskoverData Guide
theme:
    name: 'material'
    favicon: 'images/favicon.ico'
markdown_extensions:
    - mdx_breakless_lists
    - markdown_checklist.extension
extra_javascript:
    - javascript/script.js
extra_css:
    - css/style.css
